language: c

script:
  - cmake .
  - make

matrix:
  include:
    - os: osx
      osx_image: xcode9.3

    - os: linux
      addons:
        apt:
          packages:
            - cmake
            - libgtk-3-dev
