language: c

script:
  - cmake .
  - make

matrix:
  include:
    - os: osx
      osx_image: xcode9.3
      env:
        - OS_FOLDER=mac

    - os: linux
      addons:
        apt:
          packages:
            - libgtk-3-dev
            - libasound2-dev
      env:
        - OS_FOLDER=linux

after_success:
  - BUILDS_SERVER_PATH=${BUILD_SERVER}/files/$TRAVIS_BRANCH/$(date +%Y.%m.%d)/$OS_FOLDER/
  - tar -cvzf tic80.tar.gz --directory=$HOME/build/nesbox/TIC-80/bin tic80 tic80-sokol
  - curl --retry 3 --ftp-create-dirs -T tic80.tar.gz $BUILDS_SERVER_PATH/
