version: '{build}'
image: Visual Studio 2015

environment:
  matrix:
    - COMPILER: MSVC
    - COMPILER: MSVC64
    - COMPILER: MinGW-w64

install: 
  - git submodule update --init --recursive
  - if [%COMPILER%]==[MinGW-w64] set PATH=C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin;%PATH%

build_script:
  - if [%COMPILER%]==[MinGW-w64] cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_SH=CMAKE_SH-NOTFOUND .
  - if [%COMPILER%]==[MSVC] cmake -G "Visual Studio 14 2015" -DCMAKE_BUILD_TYPE=MinSizeRel .
  - if [%COMPILER%]==[MSVC64] cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=MinSizeRel .
  - cmake --build .

deploy:
  provider: S3
  access_key_id:
    secure: wO/OHsY1kAsqhKf6i/Nkdt30s7CgwW3KELrKzpD8Qb4=
  secret_access_key:
    secure: l9j5rSQDNmgj2AvqGrLQb7ii0lOLsXReThT97Dyi7IoNx8Uqm0w0hAdE1fx2bgSI
  bucket: tic80
  region: eu-central-1
  artifact: C:\projects\tic-80\bin\tic80-sokol.exe
  folder: win
  # unzip: true|false (disabled by default)
  # set_public: true|false (disabled by default)
