version: '{build}'
image: Visual Studio 2019

environment:
  matrix:
    - COMPILER: MSVC
    - COMPILER: MSVC64
  BUILD_TYPE: MinSizeRel

install: 
  - git submodule update --init --recursive

build_script:
  - mkdir out && cd out
  - if [%COMPILER%]==[MSVC] cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=%BUILD_TYPE% ..
  - if [%COMPILER%]==[MSVC64] cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=%BUILD_TYPE% ..
  - cmake --build . --parallel --config %BUILD_TYPE%

after_build:
  7z a tic80.zip %APPVEYOR_BUILD_FOLDER%\out\bin\tic80.exe

on_success:
- ps: $env:DATE=[TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow, "Belarus Standard Time").ToString('yyyy.MM.dd')
- ps: $env:TIME=[TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow, "Belarus Standard Time").ToString('HH:mm:ss')
- cmd: >-
    set BUILDS_SERVER_PATH=%BUILD_SERVER%/files/%APPVEYOR_REPO_BRANCH%/%DATE%/win
              
    curl --retry 3 --ftp-create-dirs -T tic80.zip %BUILDS_SERVER_PATH%/tic80-%COMPILER%.zip || true
