name: Build

on: [push]

env:
  BUILD_TYPE: MinSizeRel

jobs:

# === Windows x86 ===
  windows-x86:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
        fetch-depth: 0

    - name: Build
      shell: cmd
      run: |
        cd build
        cmake -G "Visual Studio 16 2019" -A Win32 -T v141_xp -DCMAKE_BUILD_TYPE=%BUILD_TYPE% ..
        cmake --build . --parallel --config %BUILD_TYPE%

    - name: Deploy
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-windows-x86.zip'
        path: build/bin/tic80.exe

# === Windows x64 ===
  windows-x64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
        fetch-depth: 0

    - name: Build
      shell: cmd
      run: |
        cd build
        cmake -G "Visual Studio 16 2019" -A x64 -T v141_xp -DCMAKE_BUILD_TYPE=%BUILD_TYPE% ..
        cmake --build . --parallel --config %BUILD_TYPE%

    - name: Deploy
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-windows-x64.zip'
        path: build/bin/tic80.exe

# === Ubuntu 16.04 ===
  ubuntu-16:
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
        fetch-depth: 0

    - name: Install
      run: sudo apt-get install libgtk-3-dev libasound2-dev libglu1-mesa-dev

    - name: Build
      run: |
        cd build
        cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
        cmake --build . --parallel --config $BUILD_TYPE
        cpack

    - name: Deploy
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-ubuntu-16.zip'
        path: build/tic80.deb

# === Ubuntu 18.04 ===
  ubuntu-18:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
        fetch-depth: 0

    - name: Install
      run: sudo apt-get install libgtk-3-dev libasound2-dev libglu1-mesa-dev

    - name: Build
      run: |
        cd build
        cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
        cmake --build . --parallel --config $BUILD_TYPE
        cpack

    - name: Deploy
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-ubuntu-18.zip'
        path: build/tic80.deb

# === MacOS 10.15 ===
  macos:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
        fetch-depth: 0

    - name: Install
      run: brew uninstall --ignore-dependencies libidn2

    - name: Build
      run: |
        cd build
        cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
        cmake --build . --parallel --config $BUILD_TYPE
        cpack
        cp *.dmg tic80.dmg

    - name: Deploy
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-macos.zip'
        path: build/tic80.dmg

# === Android arm7 arm8 x86 x86_64 ===
  android:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
        fetch-depth: 0

    - name: Build
      run: |
        cd build/android
        ./gradlew assembleRelease
        cp app/build/outputs/apk/arm7/release/app-arm7-release.apk tic80_arm7.apk
        cp app/build/outputs/apk/arm8/release/app-arm8-release.apk tic80_arm8.apk
        cp app/build/outputs/apk/x86_64/release/app-x86_64-release.apk tic80_x86_64.apk
        cp app/build/outputs/apk/x86/release/app-x86-release.apk tic80_x86.apk
        cp app/build/outputs/apk/universal/release/app-universal-release.apk tic80.apk

    - name: Deploy ARM7
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-android-arm7.zip'
        path: build/android/tic80_arm7.apk

    - name: Deploy ARM8
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-android-arm8.zip'
        path: build/android/tic80_arm8.apk

    - name: Deploy x86_64
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-android-x86_64.zip'
        path: build/android/tic80_x86_64.apk

    - name: Deploy x86
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-android-x86.zip'
        path: build/android/tic80_x86.apk

    - name: Deploy Universal
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-android.zip'
        path: build/android/tic80.apk

# === Web Assembly ===
  wasm:
    runs-on: ubuntu-latest

    steps:
    - uses: mymindstorm/setup-emsdk@v6

    - uses: actions/checkout@v2
      with: 
        submodules: recursive
        fetch-depth: 0

    - name: Build
      run: |
        cd build
        emcmake cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
        cmake --build . --parallel --config $BUILD_TYPE
        cp html/export.html bin/index.html

    - name: Deploy
      uses: actions/upload-artifact@v2
      with:
        name: 'tic80-wasm.zip'
        path: |
          build/bin/tic80.js
          build/bin/tic80.wasm
          build/bin/index.html
